### PR TITLE
Add mouse enter and mouse leave events on Advance Marker's Pin

### PR DESCRIPTION
**Pull request by aliasad106**
This allows to listen mouse over and mouse leave events on the pin of advance marker.

### CODE REVIEW

**Comment by usefulthink** [comment]
Thanks for the PR! 

Can you explain why the listeners should be added to the `Pin` instead of the `AdvancedMarker` component? The way I see it, the `Pin` is just one of many ways to use the `AdvancedMarker` and I think we should add support for the DOM events there instead.

**Comment by aliasad106** [comment]
@usefulthink  because for some reasons adding directly to AdvancedMarker doesn't work.

**Comment by usefulthink** [comment]
Ok yeah, that makes sense. I think there was something with the `pointer-events` css-property that has to be adjusted to use dom-events with the markers. I'll have a look into that.

**Comment by aliasad106** [comment]
@isaacpresidium I have created a PR but they never merged it so I am using my own forked one. You can use if you want.

**Comment by jogoley** [comment]
Can this be merged?

**Comment by usefulthink** [comment]
Thanks to @mrMetalWood, we finally have a good solution that works reliably for all types of advanced marker: #472 

Closing this as outdated.

**Pull request closed without merging**
